/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author datnsh
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Payroll extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    /**
     * Creates new form updateSalary
     */
    public Payroll() {
        initComponents();
    }
    public void Gross(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_tid = new javax.swing.JTextField();
        txt_eid = new javax.swing.JTextField();
        txt_gid = new javax.swing.JTextField();
        txt_spm = new javax.swing.JTextField();
        txt_spy = new javax.swing.JTextField();
        txt_eg = new javax.swing.JTextField();
        txt_rd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_stat = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salary Update", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("Transaction ID:");

        jLabel2.setText("Employee ID:");

        jLabel3.setText("Grade ID:");

        jLabel4.setText("Salary Per Month:");

        jLabel5.setText("Salary Per Year:");

        jLabel6.setText("Employee's Gross:");

        jLabel7.setText("Reimbursment Date:");

        jLabel8.setText("Status:");

        txt_eg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_egActionPerformed(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Return");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_spy, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_spm, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_gid, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_eid, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tid, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_eg, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(78, 78, 78)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_rd, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txt_stat))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_rd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_eid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_stat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_gid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_spm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_spy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_eg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_egActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_egActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_egActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        conn = Database.getConnection();     
        PreparedStatement pst = conn.prepareStatement("UPDATE PAYMENT.PAYROLL SET transaction_id = ?,emp_id=?,grade_id=?,emp_salary_month=?,emp_salary_year =?, emp_gross=?,reimbursment_date=?,pay_status=? WHERE transaction_id = ? ");
        PreparedStatement pst2 = conn.prepareStatement("SELECT * FROM PAYMENT.PAYGRADE WHERE grade_id=?");
        int tid = Integer.parseInt(txt_tid.getText());
        int eid = Integer.parseInt(txt_eid.getText());
        int gid = Integer.parseInt(txt_gid.getText());
        float spm = Float.parseFloat(txt_spm.getText());
        float spy = Float.parseFloat(txt_spy.getText());
        float basic;
        float ta;
        float da;
        float hra;
        float ma;
        float bonus;
        float gross = 0;
        Date rd = Date.valueOf(txt_rd.getText());
        
        pst2.setInt(1, gid);
        rs = pst2.executeQuery();
        while(rs.next()){
            basic = rs.getFloat("grade_basic");
            ta = rs.getFloat("grade_ta");
            da = rs.getFloat("grade_da");
            hra = rs.getFloat("grade_hra");
            ma = rs.getFloat("grade_ma");
            bonus = rs.getFloat("grade_bonus");
            gross = basic+ta+da+hra + ma+bonus+spm;
        }
        pst.setInt(1,tid);
        pst.setInt(2,eid);
        pst.setInt(3,gid);
        pst.setFloat(4,spm);
        pst.setFloat(5, spy);
        pst.setFloat(6,gross);
        pst.setDate(7,rd);
        pst.setString(8, txt_stat.getText());
        pst.setInt(9,tid);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Update success!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            conn=Database.getConnection();
            int id = Integer.parseInt(txt_tid.getText());
            PreparedStatement pst = conn.prepareStatement("SELECT * FROM PAYMENT.PAYROLL WHERE transaction_id = ?");
            pst.setInt(1, id);
            rs=pst.executeQuery();
            while(rs.next()){
            int tid =rs.getInt("transaction_id");
            String add1 = String.valueOf(tid);
            txt_tid.setText(add1);

            int eid =rs.getInt("emp_id");
            String add2 = String.valueOf(eid);
            txt_eid.setText(add2);

            int gid =rs.getInt("grade_id");
            String add3 = String.valueOf(gid);
            txt_gid.setText(add3);

            float spm =rs.getFloat("emp_salary_month");
            String add4 = String.valueOf(spm);
            txt_spm.setText(add4);

            float spy =rs.getFloat("emp_salary_year");
            String add5 = String.valueOf(spy);
            txt_spy.setText(add5);
            
            float gross =rs.getFloat("emp_gross");
            String add8 = String.valueOf(gross);
            txt_eg.setText(add8);
            
            Date rd =rs.getDate("reimbursment_date");
            String add6 = rd.toString();
            txt_rd.setText(add6);
            
            String add7 = rs.getString("pay_status");
            txt_stat.setText(add7);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        txt_tid.setText("");
        txt_eid.setText("");
        txt_gid.setText("");
        txt_spm.setText("");
        txt_spy.setText("");
        txt_eg.setText("");
        txt_rd.setText("");
        txt_stat.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            PreparedStatement pst2 = conn.prepareStatement("Select*FROM PAYMENT.PAYGRADE WHERE GRADE_ID = ?");
            float basic;
            float ta;
            float da;
            float hra;
            float ma;
            float bonus;
            float gross = 0;
            conn = Database.getConnection();
            int tid = Integer.parseInt(txt_tid.getText());
            int eid = Integer.parseInt(txt_eid.getText());
            int gid = Integer.parseInt(txt_gid.getText());
            float spm = Float.parseFloat(txt_spm.getText());
            float spy = Float.parseFloat(txt_spy.getText());
            String rd = txt_rd.getText();
            Date date = Date.valueOf(rd);
            pst2.setInt(1,gid);
            rs = pst2.executeQuery();
            while(rs.next()){
            basic = rs.getFloat("grade_basic");
            ta = rs.getFloat("grade_ta");
            da = rs.getFloat("grade_da");
            hra = rs.getFloat("grade_hra");
            ma = rs.getFloat("grade_ma");
            bonus = rs.getFloat("grade_bonus");
            gross = basic+ta+da+hra + ma+bonus+spm;
        }
            PreparedStatement pst = conn.prepareStatement("Insert into PAYMENT.PAYROLL values (?,?,?,?,?,?,?,?)");
            pst.setInt(1,tid);
            pst.setInt(2,eid);
            pst.setInt(3,gid);
            pst.setFloat(4,spm);
            pst.setFloat(5,spy);
            pst.setFloat(6,gross);
            pst.setDate(7, date);
            pst.setString(8,txt_stat.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data is added successfully!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_eg;
    private javax.swing.JTextField txt_eid;
    private javax.swing.JTextField txt_gid;
    private javax.swing.JTextField txt_rd;
    private javax.swing.JTextField txt_spm;
    private javax.swing.JTextField txt_spy;
    private javax.swing.JTextField txt_stat;
    private javax.swing.JTextField txt_tid;
    // End of variables declaration//GEN-END:variables
}
